run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - exportloopref
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/msgfy/linktor
  misspell:
    locale: US
  govet:
    check-shadowing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
    - path: internal/grpc/gen/
      linters:
        - all
